language: ruby
cache: bundler
os: linux

script:
  - bundle install
  - rake clean
  - rake build

deploy:
  provider: pages
  token: $GITHUB_DEPLOY_TOKEN
  local_dir: '_site'
  fqdn: www.areweinspaceyet.org
  on:
    branch: master
