language: ruby
cache: bundler
sudo: false

script:
  - bundle install
  - rake clean
  - rake build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_DEPLOY_TOKEN
  local_dir: '_site'
  fqdn: areweinspaceyet.org
  on:
    branch: master
